name: Playwright Tests with Allure

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install Allure Playwright Reporter
        run: npm install -D allure-playwright

      - name: Run Playwright Tests with Allure
        run: npx playwright test
        env:
          ALLURE_RESULTS_DIR: allure-results

      - name: Debug Allure Results Content
        run: |
          echo "--- allure-results/ folder ---"
          ls -l allure-results || echo "Missing"
          echo "--- JSON files ---"
          find allure-results -type f -name "*.json" || echo "No JSON files found"

      - name: Install Allure CLI globally
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
